# Arquivo para deploy do CESS em produção.
# VaultID - Soluções em criptografia e identidade.
# 02/01/2019
version: "3"
services:
  cess:
    image: harbor.lab.vaultid.com.br/cess/cess:1.0.49
    depends_on:
      - redis
    restart: always
    user: "33"
    environment:
      - 'clientIdMd=SEU_CLIENT_ID'
      - 'clientSecretMd=SEU_CLIENT_SECRET'
      # Se necessário, edite apenas as variávies abaixo: #
      - 'urlsMultiCloud={"https:\/\/apihom.birdid.com.br":{"id":"SOLUTI","client_id":"SEU_CLIENT_ID","client_secret":"SEU_CLIENT_SECRET"},"https:\/\/apicloudid.hom.vaultid.com.br":{"id":"VAULTID","client_id":"SEU_CLIENT_ID","client_secret":"SEU_CLIENT_SECRET"}}'
      - "signatureAdapter=MultiCloudAdapter"
      - "cessUrl=http://localhost:8080"
      - "APACHE_SSL=false"
      - "tokenValidityMAX=6"
      - "ttlCacheGeneric=21600"
      - "ttlCacheTrust=21600"
      - "lifetime=86400"
      - "sleep=100"
      - "limit=100"
      - "MEMORY_LIMIT=4096M"
      - "America/Sao_Paulo"
      - "timezone=America/Sao_Paulo"
      - 'level=INFO'
      - "redisHost=redis"
      - "redisPort=6379"

    ports:
      # Definir a PORTA_EXTERNA TCP pela qual o container será exposto na rede.
      - 8080:8080
#    volumes:
#       - ./hom-truststore:/var/www/data/trust
#      - path_crt:/etc/apache2/cert/cert.pem
#      - path_key:/etc/apache2/cert/cert.key
    networks:
      - nw-cess
  redis:
    image: "healthcheck/redis:alpine"
    restart: always
    networks:
      - nw-cess
networks:
  nw-cess:
    driver: bridge
    ipam:
      driver: default
