# Arquivo para deploy do CESS em produção.
# VaultID - Soluções em criptografia e identidade.
# 27/02/2019
version: "3"
services:
  cess:
    image: harbor.lab.vaultid.com.br/cess/cess:1.0.18-rc2
    depends_on:
      - redis
    restart: always
    user: "33"
    environment:
      - "debug=false"
      - "vaultCloudUrl=https://apicloudid.vaultid.com.br"
      - "actTSA=http://act1.vaultid.com.br:9318"
      - "version=1.0.18-rc2"
      # Se necessário, edite apenas as variávies abaixo: #
      - "cessUrl=http://localhost:8080"
      - "APACHE_SSL=false"
      # Configuração para HSM local.
      - "signatureAdapter=DinamoPkcs12Adapter"
      - "hsmIp=IP_HSM"
      - "hsmPort=4433"
      - "zSlotManagerUser=false"
      - "zSlotManagerPw=false"
      - "tokenValidityMAX=6"
      - "ttlCacheGeneric=21600"
      - "ttlCacheTrust=21600"
      - "lifetime=86400"
      - "sleep=100"
      - "limit=50"
      - "cacheDir=/var/www/data/files/cache"
      - "HSM_LOAD_BALANCE_LIST="
    ports:
      # Definir a PORTA_EXTERNA TCP pela qual o container será exposto na rede.
      - PORTA_EXTERNA:8080
    volumes:
#      - path_crt:/etc/apache2/cert/cert.pem
#      - path_key:/etc/apache2/cert/cert.key
      - path_p12:/var/www/certs
    networks:
      - nw-cess
  redis:
    image: "healthcheck/redis:alpine"
    restart: always
    networks:
      - nw-cess
networks:
  nw-cess:
    driver: bridge
    ipam:
      driver: default
